# Dataset / loader parameters
dataset_name: "qm9"
data_path: /scratch/gpfs/ROSENGROUP/common/globus_share_OA/qm9/data/tzvp200_atomh1e_smallerbox/results/
label_path: /scratch/gpfs/ROSENGROUP/common/globus_share_OA/qm9/label/szv50_tzvp200_smallerbox
rho_type: chgcar
train_fraction: 0.9
num_workers: 1
downsample_label: 1
downsample_data: 1
data_augmentation: False
random_state: 42
normalize: True
data_precision: f32

# Model parameters
n_channels: 32
n_residual_blocks: 32
n_upscale_layers: 0
kernel_size1: 5
kernel_size2: 5
model_prefix: chk
model_precision: 32 # 16 means bfloat16

# Training parameters
save_every_epochs: 2
epochs: 100
nbatch: 1
lr: 0.01
weight_decay: 0.0

# Weights and biases
wb_pname: "electrai-initial-tests"
wb_ename: "qm9-no-image-upscaling"
entity: "PrinceOA"

#Profiler
profile_dir: /scratch/gpfs/ROSENGROUP/ho0950/electrai/profiles
