#!/usr/bin/env python3
"""Generate per-trial configs for the LR/weight-decay width sweep.

Derives each trial from the CoreWeave production config
(config_gga_gga+u_w96.yaml) with only these deltas: width, lr, weight_decay,
optimizer, the compressed 8-epoch schedule, the 12K sweep split files, and
per-trial run/ckpt names. Design rationale: docs/lr_wd_width_sweep.md.

Stage A — LR grid at wd=0:

    uv run python scripts/coreweave/gen_lrwd_sweep.py --stage a

Stage B — WD grid at the per-width best LR from stage A, plus one
(lr*/2, wd=1e-3) cross term and a verbatim rerun of the stage-A anchor to
measure run-to-run noise:

    uv run python scripts/coreweave/gen_lrwd_sweep.py --stage b \
        --best-lr 32=0.002 64=0.001 96=0.0005

Configs land in src/electrai/configs/MP/sweep_lrwd/; matching submit.sh
commands are printed but NOT executed.
"""

from __future__ import annotations

import argparse
import copy
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
BASE_CONFIG = REPO / "src/electrai/configs/MP/config_gga_gga+u_w96.yaml"
OUT_DIR = REPO / "src/electrai/configs/MP/sweep_lrwd"

WIDTHS = [32, 64, 96]
STAGE_A_LRS = [2.5e-4, 5e-4, 1e-3, 2e-3, 4e-3]
STAGE_B_WDS = [1e-4, 1e-3, 1e-2]

SWEEP_EPOCHS = 8
SWEEP_WARMUP = 1
WB_PROJECT = "mp-gga-ggau-lrwd"
# Repo-relative: bundled in the submit.sh zip and read from the job workdir,
# so warm nodes whose .staged.ok marker skips the bucket sync still see them.
SWEEP_SPLITS = {
    "gga+u": "data/MP/sweep_splits/gga+u_split_sweep12k.json",
    "gga": "data/MP/sweep_splits/gga_split_sweep12k.json",
}


def fmt(x: float) -> str:
    return f"{x:g}"


def make_trial(base: dict, width: int, lr: float, wd: float, suffix: str = "") -> str:
    cfg = copy.deepcopy(base)
    cfg["model"]["n_channels"] = width
    cfg["lr"] = lr
    cfg["weight_decay"] = wd
    cfg["optimizer"] = "adamw" if wd > 0 else "adam"
    cfg["epochs"] = SWEEP_EPOCHS
    cfg["warmup_length"] = SWEEP_WARMUP
    cfg["wb_pname"] = WB_PROJECT
    for ds in cfg["data"]["datasets"]:
        functional = next(f for f in SWEEP_SPLITS if f"/{f}/" in ds["root"])
        ds["split_file"] = SWEEP_SPLITS[functional]

    stem = f"sweep_lrwd_w{width}_lr{fmt(lr)}_wd{fmt(wd)}{suffix}"
    cfg["run_name"] = stem
    # Own stem => own ckpt namespace; a reused stem would resume from the
    # earlier trial's last.ckpt in the bucket.
    cfg["ckpt_path"] = f"/uv/cache/electrai/checkpoints/{stem}"

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUT_DIR / f"{stem}.yaml"
    with path.open("w") as fp:
        fp.write(
            f"# Generated by scripts/coreweave/gen_lrwd_sweep.py from {BASE_CONFIG.name}\n"
        )
        fp.write(
            "# Deltas: width/lr/wd/optimizer, 8-epoch schedule, 12K sweep splits.\n"
        )
        yaml.safe_dump(cfg, fp, sort_keys=False)
    return stem


def parse_best_lr(pairs: list[str]) -> dict[int, float]:
    best = {}
    for pair in pairs:
        w, _, lr = pair.partition("=")
        best[int(w)] = float(lr)
    missing = set(WIDTHS) - set(best)
    if missing:
        raise SystemExit(f"--best-lr missing widths: {sorted(missing)}")
    return best


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stage", choices=["a", "b"], required=True)
    parser.add_argument(
        "--best-lr",
        nargs="*",
        default=[],
        metavar="WIDTH=LR",
        help="stage b: per-width best LR from stage a, e.g. 32=0.002",
    )
    args = parser.parse_args()

    with BASE_CONFIG.open() as fp:
        base = yaml.safe_load(fp)

    stems = []
    if args.stage == "a":
        stems = [
            make_trial(base, width, lr, 0.0) for width in WIDTHS for lr in STAGE_A_LRS
        ]
    else:
        best = parse_best_lr(args.best_lr)
        for width in WIDTHS:
            lr = best[width]
            stems.extend(make_trial(base, width, lr, wd) for wd in STAGE_B_WDS)
            stems.append(make_trial(base, width, lr / 2, 1e-3))
            stems.append(make_trial(base, width, lr, 0.0, suffix="_rep2"))

    print(f"Wrote {len(stems)} configs to {OUT_DIR}\n")
    print("Submit (from a clean worktree, one job per trial):")
    for stem in stems:
        job = "el-" + stem.removeprefix("sweep_lrwd_").replace(".", "p").replace(
            "_", "-"
        )
        print(
            f"  scripts/coreweave/submit.sh src/electrai/configs/MP/sweep_lrwd/{stem}.yaml {job}"
        )


if __name__ == "__main__":
    main()
